### PR TITLE
fix keywords

### PR DESCRIPTION
**Pull request by calvinmetcalf**
you try to create the keywords array by concating the words array to the (not yet created) keyword array

### CODE REVIEW

**Comment by jprichardson** [comment]
I must be missing what you're trying to do... it's intentional behavior to concatenate to the array. Are you experiencing an error?

**Comment by calvinmetcalf** [comment]
you are trying to concat data to the array data.keywords before data.keywords exists, or will be able to exist as far as I can tell.

**Comment by jprichardson** [comment]
Ahh, I see. Your fix removes the concat behavior... I'll modify it. Thanks.

**Comment by calvinmetcalf** [comment]
I removed it because as far as I could tell it would never _need_ to be
concated right there

On Mon, Dec 2, 2013 at 8:49 AM, JP Richardson notifications@github.comwrote:

> Ahh, I see. Your fix removes the concat behavior... I'll modify it. Thanks
> it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jprichardson/tin/pull/10#issuecomment-29618514
> .

## 

-Calvin W. Metcalf

**Comment by jprichardson** [comment]
Fixed it. Didn't accept the PR because it removed the concat ability. Thanks so much for your interest and for pointing out the bug!

**Pull request closed without merging**
